baseURL = 'https://michalchng.github.io/'
languageCode = 'en-us'
title = 'michalchng'
theme = "papermod"
publishDir = "docs"

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[params.homeInfoParams]
Title = "Welcome to my blog!"
Content = "I'm Michael and this is where I plan to share a variety of sporting equipment reviews while testing out the features of hugo sites."

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/m_chenger/"
[[params.socialIcons]]
name = "strava"
url = "https://www.strava.com/athletes/30742046"
[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/michael-a-cheng/"
[[params.socialIcons]]
name = "github"
url = "https://github.com/michalchng"
